"""Answer cache for `/chat` and pre-generated handovers, so the demo never needs a live LLM call
on the free tier.

Chat: keyed on (language, normalised question). A hit is served without calling the LLM. Entries
remember the knowledge-base version they were answered from (a hash of backend/kb/*.md); after a
kb edit they are ignored until re-generated. Two files in backend/cache/:
* `demo.json` (committed): answers and handover summaries pre-generated by
  `scripts/prewarm_demo.py`. Read-only at runtime.
* `chat_runtime.json` (gitignored): answers the running server adds; the oldest go past
  `MAX_RUNTIME` entries.

Matching is exact on the normalised text on purpose: a fuzzy match could answer "What does E-360
mean?" (low oil, possible leak) with the cached E-365 (hot oil) answer.
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import re
import tempfile
import threading
import unicodedata
from collections import OrderedDict
from datetime import UTC, datetime
from functools import lru_cache
from pathlib import Path
from typing import Any

from app.services.kb import DOC_TYPES, KB_DIR

log = logging.getLogger(__name__)

CACHE_DIR = Path(__file__).resolve().parents[2] / "cache"
DEMO_FILE = CACHE_DIR / "demo.json"
RUNTIME_FILE = CACHE_DIR / "chat_runtime.json"
MAX_RUNTIME = 200

_CODE = re.compile(r"\be\s*-?\s*(\d{3})\b")  # "E365", "e 365", "E-365" -> "e-365"


def normalise(question: str) -> str:
    q = unicodedata.normalize("NFKC", question).casefold()
    q = _CODE.sub(r"e-\1", q)
    # Drop punctuation and symbols only. Letters, digits and combining marks stay: a regex \w
    # would drop Devanagari and Tamil vowel signs and merge different words into one key.
    q = "".join(c if c == "-" or unicodedata.category(c)[0] in "LMN" else " " for c in q)
    return " ".join(q.split())


def key(question: str, language: str) -> str:
    return f"{language}|{normalise(question)}"


def kb_version(kb_dir: Path = KB_DIR) -> str:
    h = hashlib.sha256()
    for f in DOC_TYPES:
        path = kb_dir / f
        if path.exists():
            h.update(f.encode())
            h.update(path.read_bytes().replace(b"\r\n", b"\n"))
    return h.hexdigest()[:12]


def _read(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {}
    except (OSError, ValueError) as e:
        log.error("chat cache %s unreadable, ignoring it: %s", path, e)
        return {}


def _write(path: Path, data: dict[str, Any]) -> None:
    """Atomic: a crash mid-write never leaves a half file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, suffix=".tmp")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write("\n")
    os.replace(tmp, path)


class ChatCache:
    def __init__(self, demo_file: Path | None = None, runtime_file: Path | None = None) -> None:
        self.demo_file = demo_file or DEMO_FILE
        self.runtime_file = runtime_file or RUNTIME_FILE
        self.version = kb_version()
        self._lock = threading.Lock()
        self._demo: dict[str, Any] = _read(self.demo_file).get("chat", {})
        self._runtime: OrderedDict[str, Any] = OrderedDict(_read(self.runtime_file).get("chat", {}))

    def get(self, question: str, language: str) -> dict[str, Any] | None:
        """{answer, sources, ...} for this question, or None (missing or older kb)."""
        k = key(question, language)
        with self._lock:
            entry = self._demo.get(k) or self._runtime.get(k)
            if entry is None or entry.get("kb_version") != self.version:
                return None
            if k in self._runtime:
                self._runtime.move_to_end(k)
            return entry

    def put(self, question: str, language: str, answer: str, sources: list[dict[str, Any]]) -> None:
        k = key(question, language)
        entry = {
            "question": question,
            "language": language,
            "answer": answer,
            "sources": sources,
            "kb_version": self.version,
            "created_at": datetime.now(UTC).isoformat(),
        }
        with self._lock:
            self._runtime[k] = entry
            self._runtime.move_to_end(k)
            while len(self._runtime) > MAX_RUNTIME:
                self._runtime.popitem(last=False)
            data = {"chat": dict(self._runtime)}
            try:
                _write(self.runtime_file, data)
            except OSError as e:  # the answer still went out; only persistence failed
                log.error("chat cache write failed: %s", e)


def read_demo(demo_file: Path | None = None) -> dict[str, Any]:
    return _read(demo_file or DEMO_FILE)


def write_demo(data: dict[str, Any], demo_file: Path | None = None) -> None:
    _write(demo_file or DEMO_FILE, data)


def demo_handovers(demo_file: Path | None = None) -> dict[str, str]:
    """shift_id -> pre-generated handover summary."""
    return {sid: h["summary"] for sid, h in read_demo(demo_file).get("handovers", {}).items()}


@lru_cache
def get_chat_cache() -> ChatCache:
    return ChatCache()
